### ISSUE TITLE
Build step/Install step

### ISSUE THREAD

**Issue by akinsho** [jordan-arenstein/oni-plugin-touchbar#5]
@jordan-arenstein this is amazing btw I'm currently looking to update the `README` so its more discoverable until we have a better plugin discovery UI.

Atm to get the plugin to work a user has to clone this into the plugins dir (which is the current state of affairs with Oni) however there is also an added step of running `tsc -p tsconfig.json` I wonder if this can be added to the package.json as
```json
	build: "tsc -p tsconfig.json"
```

**Comment by jordan-arenstein** [comment]
Hey @Akin909, thanks for the suggestion! I'll add it in now.
